import { NumberScale } from '../types/calculator';

export const numberScales: NumberScale[] = [
  { value: 1e93, symbol: 'Tg', name: 'Trigintillion' },
  { value: 1e90, symbol: 'NVg', name: 'Nonvigintillion' },
  { value: 1e87, symbol: 'OVg', name: 'Octovigintillion' },
  { value: 1e84, symbol: 'SpVg', name: 'Septvigintillion' },
  { value: 1e81, symbol: 'SxVg', name: 'Sexvigintillion' },
  { value: 1e78, symbol: 'QnVg', name: 'Quinvigintillion' },
  { value: 1e75, symbol: 'QtVg', name: 'Quattuorvigintillion' },
  { value: 1e72, symbol: 'TVg', name: 'Trevigintillion' },
  { value: 1e69, symbol: 'DVg', name: 'Duovigintillion' },
  { value: 1e66, symbol: 'UVg', name: 'Unvigintillion' },
  { value: 1e63, symbol: 'Vg', name: 'Vigintillion' },
  { value: 1e60, symbol: 'Nd', name: 'Novemdecillion' },
  { value: 1e57, symbol: 'Od', name: 'Octodecillion' },
  { value: 1e54, symbol: 'Spd', name: 'Septemdecillion' },
  { value: 1e51, symbol: 'Sxd', name: 'Sexdecillion' },
  { value: 1e48, symbol: 'Qnd', name: 'Quindecillion' },
  { value: 1e45, symbol: 'Qtd', name: 'Quattuordecillion' },
  { value: 1e42, symbol: 'Td', name: 'Tredecillion' },
  { value: 1e39, symbol: 'Dd', name: 'Duodecillion' },
  { value: 1e36, symbol: 'Ud', name: 'Undecillion' },
  { value: 1e33, symbol: 'D', name: 'Decillion' },
  { value: 1e30, symbol: 'N', name: 'Nonillion' },
  { value: 1e27, symbol: 'O', name: 'Octillion' },
  { value: 1e24, symbol: 'Sp', name: 'Septillion' },
  { value: 1e21, symbol: 'Sx', name: 'Sextillion' },
  { value: 1e18, symbol: 'Qi', name: 'Quintillion' },
  { value: 1e15, symbol: 'Q', name: 'Quadrillion' },
  { value: 1e12, symbol: 'T', name: 'Trillion' },
  { value: 1e9, symbol: 'B', name: 'Billion' },
  { value: 1e6, symbol: 'M', name: 'Million' },
];